from __future__ import annotations

import tempfile
import time
import unittest
from pathlib import Path
from urllib.request import Request, urlopen
import json

from apex_code.application import ApexApplication
from apex_code.contract import RuntimeExecution, RuntimeFact, RuntimeIdentity, RuntimePreparation


class ShellAdapter:
    model = "shell-test-model"

    def materialize_authority(self, authority_digest: str) -> RuntimePreparation:
        return RuntimePreparation("prep_shell", authority_digest, tempfile.mkdtemp(prefix="apex-shell-authority-"), "CORE_MEDIATED_NO_RUNTIME_IO")

    def execute(self, prompt: str, workspace: Path, preparation: RuntimePreparation) -> RuntimeExecution:
        return RuntimeExecution(
            identity=RuntimeIdentity(session_id="shell-session", process_id=42, adapter_instance_id="shell-adapter"),
            fact=RuntimeFact.EXITED,
            exit_code=0,
            text="REPORT_CONTENT_BEGIN\n# Shell report\nGenerated by Core.\nREPORT_CONTENT_END",
            event_count=1,
            preparation_id=preparation.preparation_id,
            authority_config_digest=preparation.authority_digest,
            command=("shell-fake", "<prompt>"),
        )


class ApplicationTests(unittest.TestCase):
    def test_submission_uses_core_and_history_survives_service_reload(self) -> None:
        with tempfile.TemporaryDirectory() as root:
            workspace = Path(root)
            (workspace / "README.md").write_text("# Shell project\n", encoding="utf-8")
            (workspace / ".env.dev").write_text("sentinel-not-for-display\n", encoding="utf-8")
            application = ApexApplication(ShellAdapter())
            try:
                project = application.open_project(workspace)
                self.assertTrue(project["selected"])
                self.assertNotIn(".env.dev", {entry["name"] for entry in project["entries"]})
                submission = application.submit_task("report")
                self.assertTrue(submission["job_id"].startswith("shell_"))
                for _ in range(40):
                    status = application.status()
                    if status.get("state") == "SUCCEEDED":
                        break
                    time.sleep(0.01)
                self.assertIsNotNone(status["execution"])
                self.assertEqual(status["state"], "SUCCEEDED")
                self.assertTrue(status["execution"]["semantic_success"])
                reloaded = ApexApplication(ShellAdapter())
                try:
                    reloaded.open_project(workspace)
                    self.assertEqual(reloaded.history()["executions"][0]["attempt_id"], status["execution"]["attempt_id"])
                    for _ in range(20):
                        try:
                            artifact = reloaded.artifact("REPORT.md")
                            break
                        except Exception:
                            time.sleep(0.01)
                    else:
                        self.fail("Core artifact was not visible after successful execution")
                    self.assertIn("Shell report", artifact["content"])
                finally:
                    reloaded.close()
            finally:
                application.close()

    def test_http_boundary_exposes_queries_and_bounded_command(self) -> None:
        with tempfile.TemporaryDirectory() as root:
            workspace = Path(root)
            (workspace / "README.md").write_text("# HTTP shell\n", encoding="utf-8")
            application = ApexApplication(ShellAdapter())
            from apex_code.shell import ShellServer
            server = ShellServer(("127.0.0.1", 0), application)
            import threading

            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            base = f"http://127.0.0.1:{server.server_address[1]}"
            try:
                request = Request(base + "/api/project", data=json.dumps({"path": str(workspace)}).encode(), headers={"Content-Type": "application/json"}, method="POST")
                with urlopen(request) as response:
                    self.assertEqual(response.status, 200)
                request = Request(base + "/api/tasks", data=b'{"task":"report"}', headers={"Content-Type": "application/json"}, method="POST")
                with urlopen(request) as response:
                    self.assertEqual(response.status, 202)
                for _ in range(40):
                    with urlopen(base + "/api/status") as response:
                        status = json.load(response)
                    if status.get("state") == "SUCCEEDED":
                        break
                    time.sleep(0.01)
                self.assertEqual(status["state"], "SUCCEEDED")
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=2)


if __name__ == "__main__":
    unittest.main()
