from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from apex_code.cli import main
from apex_code.contract import RuntimeExecution, RuntimeFact, RuntimeIdentity, RuntimePreparation


class CliAdapter:
    model = "cli-test-model"

    def materialize_authority(self, authority_digest: str) -> RuntimePreparation:
        return RuntimePreparation("prep_cli", authority_digest, tempfile.mkdtemp(prefix="apex-cli-authority-"), "CORE_MEDIATED_NO_RUNTIME_IO")

    def execute(self, prompt: str, workspace: Path, preparation: RuntimePreparation) -> RuntimeExecution:
        return RuntimeExecution(
            identity=RuntimeIdentity(session_id="cli-session"),
            fact=RuntimeFact.EXITED,
            exit_code=0,
            text="SUMMARY_CONTENT_BEGIN\n# CLI summary\nGenerated by the CLI test.\nSUMMARY_CONTENT_END",
            event_count=1,
            preparation_id=preparation.preparation_id,
            authority_config_digest=preparation.authority_digest,
            command=("fake", "<prompt>"),
        )


class CliTests(unittest.TestCase):
    def test_summary_task_is_selectable_without_changing_default_contract(self) -> None:
        with tempfile.TemporaryDirectory() as root:
            workspace = Path(root)
            (workspace / "README.md").write_text("# CLI example\n", encoding="utf-8")
            argv = ["apex-code", str(workspace), "--task", "summary"]
            with patch.object(sys, "argv", argv), patch(
                "apex_code.runtime.OpenCodeRuntimeAdapter", return_value=CliAdapter()
            ), patch("builtins.print") as output:
                self.assertEqual(main(), 0)
            result = json.loads(output.call_args.args[0])
            self.assertEqual(result["artifact"], "SUMMARY.md")
            self.assertTrue(result["semantic_success"])
            self.assertTrue((workspace / "SUMMARY.md").is_file())
            self.assertFalse((workspace / "REPORT.md").exists())


if __name__ == "__main__":
    unittest.main()
